marble defconfig: Explicitly disable `CONFIG_TCP_CONG_BIC`
- The default value of `CONFIG_TCP_CONG_BIC` is m, meaning it will be
  compiled as a module, but we don't actually use it because CUBIC is
  better.
- This suppresses the warning from `compare_to_symbol_list` (from the GKI compilation tools):
  ERROR: Differences between ksymtab and symbol list detected!
  Symbols missing from ksymtab:
  Symbols missing from symbol list:
   - tcp_cong_avoid_ai