Revert "net: openvswitch: conntrack: avoid modifying shared unconfirmed ct entry"
../include/net/netfilter/nf_conntrack.h:178:23: error: incompatible pointer types passing 'const atomic_t *' to parameter of type 'const refcount_t *' (aka 'const struct refcount_struct *') [-Werror,-Wincompatible-pointer-types]
        return refcount_read(&ct->ct_general.use) > 1;
                             ^~~~~~~~~~~~~~~~~~~
../include/linux/refcount.h:145:60: note: passing argument to parameter 'r' here
static inline unsigned int refcount_read(const refcount_t *r)
                                                           ^

Since we don't have commit f483ed6e8c4e3e1046e29b16a68b5bc8ca103eef.

This reverts commit e0fa5ea434b7e8467ef3adc64e3858b1ca2a642d.